services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'  # Adjust based on your CPU
        reservations:
          cpus: '2'  # Minimum CPU allocation

volumes:
  ollama_data: 